/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package email;

import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        pswd = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        back = new javax.swing.JButton();
        fp = new javax.swing.JLabel();
        openeye = new javax.swing.JLabel();
        closedeye = new javax.swing.JLabel();
        viewpassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("UserName:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 180, 100, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 220, 100, 30);

        un.setBackground(new java.awt.Color(204, 204, 255));
        un.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        un.setText("abc123@gmail.com");
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        jPanel1.add(un);
        un.setBounds(180, 180, 210, 30);

        pswd.setBackground(new java.awt.Color(204, 204, 255));
        pswd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdActionPerformed(evt);
            }
        });
        jPanel1.add(pswd);
        pswd.setBounds(180, 220, 210, 30);

        login.setBackground(new java.awt.Color(0, 51, 255));
        login.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(230, 300, 100, 30);

        back.setBackground(new java.awt.Color(0, 51, 255));
        back.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(60, 120, 90, 30);

        fp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fp.setForeground(new java.awt.Color(0, 0, 102));
        fp.setText("Forget Password");
        fp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpMouseClicked(evt);
            }
        });
        jPanel1.add(fp);
        fp.setBounds(230, 350, 120, 30);

        openeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openeyeMouseClicked(evt);
            }
        });
        jPanel1.add(openeye);
        openeye.setBounds(400, 220, 30, 23);

        closedeye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closedeyeMouseClicked(evt);
            }
        });
        jPanel1.add(closedeye);
        closedeye.setBounds(400, 220, 27, 24);
        jPanel1.add(viewpassword);
        viewpassword.setBounds(180, 220, 200, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("LOGIN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 40, 140, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        try {
          Statement s =(Statement) db.mycon().createStatement();
          String unv = un.getText();
          String pswdv = pswd.getText();
          String mp = "";
          unv=encription.encrpfun(unv);
          pswdv=encription.encrpfun(pswdv);
          ResultSet rs = s.executeQuery("Select * from account where username = '"+unv+"';");
        
          if(rs.next()){
              mp=rs.getString("password");
              if(mp.equals(pswdv)){
              unv=decription.decrpfun(unv);
              JOptionPane.showMessageDialog(null,"Success! Logged in with USERNAME: "+unv);
              homepageemail jf1 = new homepageemail();
              jf1.my_update(unv);
              jf1.setVisible(true);
              dispose();
                }
            else{
                JOptionPane.showMessageDialog(null,"Incorrect Password!");
            }
          }
          else{
                JOptionPane.showMessageDialog(null,"Incorrect Username!");
            }
         s.close();
      } 
      catch (SQLException e) {
        System.out.println(e);  
      }
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dispose();
        Home2 jf1 = new Home2();
        jf1.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void fpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpMouseClicked
        // TODO add your handling code here:
        dispose();
        forgotpass jf1 = new forgotpass();
        jf1.setVisible(true);
    }//GEN-LAST:event_fpMouseClicked

    private void openeyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openeyeMouseClicked
        // TODO add your handling code here:
        viewpassword.setText(pswd.getText());
        pswd.setVisible(false);
        viewpassword.setVisible(true);
        openeye.setVisible(false);
        closedeye.setVisible(true);
    }//GEN-LAST:event_openeyeMouseClicked

    private void closedeyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closedeyeMouseClicked
        // TODO add your handling code here:
        pswd.setText(viewpassword.getText());
        viewpassword.setVisible(false);
        pswd.setVisible(true);
        openeye.setVisible(true);
        closedeye.setVisible(false);
    }//GEN-LAST:event_closedeyeMouseClicked

    private void pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel closedeye;
    private javax.swing.JLabel fp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel openeye;
    private javax.swing.JPasswordField pswd;
    private javax.swing.JTextField un;
    private javax.swing.JTextField viewpassword;
    // End of variables declaration//GEN-END:variables
}
